#!/usr/bin/env tsx
/**
 * scripts/update-hanh-chinh.ts
 *
 * Script cập nhật danh sách mã đơn vị hành chính Việt Nam.
 * Chạy sau khi có nghị quyết sáp nhập tỉnh thành chính thức:
 *
 *   npx tsx scripts/update-hanh-chinh.ts
 *
 * Nguồn dữ liệu chính thống:
 *   - https://dmhc.gov.vn (Danh mục hành chính)
 *   - Nghị quyết UBTVQH về sắp xếp đơn vị hành chính
 *
 * ⚠️  SAU KHI CHẠY SCRIPT NÀY:
 *   1. Review diff trong src/lib/vn/hanh-chinh.ts
 *   2. Cập nhật unit tests trong src/lib/vn/__tests__/validators.test.ts
 *   3. Kiểm tra lại toàn bộ CCCD đã lưu trong database
 *   4. Thông báo cho team về mã tỉnh mới
 *
 * Theo dõi: Dự kiến sáp nhập từ 63 → 34 tỉnh/thành vào năm 2025-2026
 * Xem thêm: IMPROVEMENT_GUIDE.md > Q1 2026 > Cập nhật mã tỉnh
 */

import { writeFileSync } from "fs";
import { resolve } from "path";

// Định nghĩa cấu trúc dữ liệu
interface TinhInput {
  ma: string;
  ten: string;
  tenViet: string;
  vung: "Bắc" | "Trung" | "Nam";
  capTinh: "Thành phố trực thuộc TW" | "Tỉnh";
  hieuLuc?: boolean;
}

/**
 * Dữ liệu mẫu — sau sáp nhập (MÔ PHỎNG — cần cập nhật theo nghị quyết chính thức).
 *
 * ⚠️  ĐÂY LÀ DỮ LIỆU MÔ PHỎNG — chưa có nghị quyết chính thức.
 *     Thay bằng dữ liệu thực khi có nghị quyết.
 *
 * Nguồn tham khảo đề xuất sáp nhập:
 *   - Kết luận 48-KL/TW ngày 30/01/2023 của Bộ Chính trị
 *   - Nghị quyết 37-NQ/TW về sắp xếp đơn vị hành chính
 */
const DU_LIEU_SAU_SAP_NHAP_MAU: TinhInput[] = [
  // Miền Bắc (sau sáp nhập dự kiến ~13 tỉnh/thành)
  { ma: "001", ten: "Thành phố Hà Nội (mở rộng)", tenViet: "Ha Noi",   vung: "Bắc", capTinh: "Thành phố trực thuộc TW" },
  { ma: "031", ten: "Thành phố Hải Phòng (mở rộng)", tenViet: "Hai Phong", vung: "Bắc", capTinh: "Thành phố trực thuộc TW" },
  // ... (cần bổ sung theo nghị quyết chính thức)
];

function taoFileHanhChinh(danhSach: TinhInput[]): string {
  const entries = danhSach.map((t) => `  { ma: "${t.ma}", ten: "${t.ten}", tenViet: "${t.tenViet}", vung: "${t.vung}", capTinh: "${t.capTinh}", hieuLuc: ${t.hieuLuc !== false} }`);

  return `// AUTO-GENERATED by scripts/update-hanh-chinh.ts — ${new Date().toISOString()}
// KHÔNG SỬA TRỰC TIẾP — chạy script để cập nhật
// Phiên bản: ${new Date().toLocaleDateString("vi-VN")}

export const DANH_SACH_TINH_MOI = [
${entries.join(",\n")}
] as const;
`;
}

// Kiểm tra tính nhất quán dữ liệu
function kiemTraDuLieu(danhSach: TinhInput[]): void {
  const maDaDung = new Set<string>();
  const loi: string[] = [];

  for (const tinh of danhSach) {
    // Kiểm tra độ dài mã: phải là 3 chữ số
    if (!/^\d{3}$/.test(tinh.ma)) {
      loi.push(`Mã tỉnh "${tinh.ma}" (${tinh.ten}) phải là 3 chữ số`);
    }
    // Kiểm tra trùng lặp
    if (maDaDung.has(tinh.ma)) {
      loi.push(`Mã tỉnh "${tinh.ma}" bị trùng lặp`);
    }
    maDaDung.add(tinh.ma);
    // Kiểm tra tên không rỗng
    if (!tinh.ten.trim()) {
      loi.push(`Tên tỉnh cho mã "${tinh.ma}" không được để trống`);
    }
  }

  if (loi.length > 0) {
    console.error("❌ Lỗi trong dữ liệu hành chính:");
    loi.forEach((l) => console.error(`   - ${l}`));
    process.exit(1);
  }
}

// Main
function main() {
  console.log("🔄 Kiểm tra dữ liệu hành chính...");
  kiemTraDuLieu(DU_LIEU_SAU_SAP_NHAP_MAU);
  console.log(`✅ Dữ liệu hợp lệ — ${DU_LIEU_SAU_SAP_NHAP_MAU.length} đơn vị hành chính`);

  // Chỉ tạo file preview — không ghi đè hanh-chinh.ts trực tiếp
  const outputPath = resolve(process.cwd(), "src/lib/vn/hanh-chinh-moi.preview.ts");
  writeFileSync(outputPath, taoFileHanhChinh(DU_LIEU_SAU_SAP_NHAP_MAU), "utf-8");

  console.log(`\n📄 Preview đã được tạo: ${outputPath}`);
  console.log("⚠️  Review file preview, sau đó copy vào hanh-chinh.ts thủ công.");
  console.log("⚠️  Cập nhật unit tests sau khi thay đổi mã tỉnh!");
  console.log("\n✅ Hoàn tất. Các bước tiếp theo:");
  console.log("   1. npx tsc --noEmit   (kiểm tra TypeScript)");
  console.log("   2. npx tsx --test src/lib/vn/__tests__/validators.test.ts");
  console.log("   3. npm run build");
}

main();
